name: package testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install TypeScript globally
        run: npm install -g typescript

      - name: Check Yarn version
        run: yarn --version
      - name: Check Node version
        run: node --version
      - name: Install dependencies
        run: yarn install
      - name: Execute lint
        run: yarn lint
      - name: Build package
        run: yarn build
      - name: Test packages
        run: yarn test
